# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  projectDir: "$(System.DefaultWorkingDirectory)/EnvTestDemo/"
  projectFile: "$(projectDir)/EnvTestDemo.csproj"

steps:
- task: DotNetCoreCLI@2
  displayName: "dotnet build"
  inputs:
    command: build
    projects: $(projectFile)
    arguments: '--configuration $(buildConfiguration)'
   
- task: DotNetCoreCLI@2
  displayName: "dotnet publish"
  inputs:
    command: publish
    projects: $(projectFile)
    arguments: --configuration $(buildConfiguration) --output publish_output
    zipAfterPublish: false
    publishWebProjects: false
    modifyOutputPath: true

- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output/EnvTestDemo/"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"

- task: PublishPipelineArtifact@1
  displayName: "publish artifact"
  inputs:
    path: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
    artifact: EnvTestDemo
